skills = ["Unarmed",
          "Blunt",
          "Sharp",
          "Pierce",
          "Ranged",
          "Two-Handed",
          "Dual-Wielding",
          "Jump",
          "Climb",
          "Swim",
          "Parkour",
          "Dodge",
          "Pick Pocket",
          "Lie",
          "Persuade",
          "Seduce",
          "Hide",
          "Move Silently",
          "Sense Motive",
          "Search",
          "Knowledge",
          "Craft Mundane",
          "Craft Magical",
          ]